version: '2'

services:
  locserver:
    restart: always
    image: aieyes/locserver:9.13.0-20191126
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    - "22:22/tcp"
    - "21:21/tcp"
    - "80:80/tcp"
    volumes:
    - /srv/docker/locserver:/data
