apiVersion: v1
kind: Pod
metadata:
  name: bindftp
  labels:
    name: bindftp
spec:
  containers:
    - name: bindftp
      image: omofresh/bindftp
      env:
        - name: WEBMIN_ENABLED
          value: false
      ports:
        - containerPort: 53
          protocol: UDP
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      emptyDir: {}
