apiVersion: v1
kind: Service
metadata:
  name: bindftp
  labels:
    name: bindftp
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
  selector:
    name: bindftp
