apiVersion: v1
kind: Service
metadata:
  name: locserver
  labels:
    name: locserver
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
  selector:
    name: locserver
